//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Agenda.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//
using System;

namespace HospiEnCasa.App.Dominio
{
	public class Agenda 
	{
		public DateTime Fecha { get; set; }
		public string Hora { get; set; }
		public string Sede { get; set; }
		public string Servicio { get; set; }
		public string TipoCita { get; set; }
		public string Medico { get; set; }
		public string Consultorio { get; set; }
		public string Estado { get; set; }
		public string IdPte { get; set; }
		public int Vr_Consulta { get; set; }
	}
}

