//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuenta.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//
using System;

namespace HospiEnCasa.App.Dominio
{
	public class Cuenta 
	{
		public string IdUsuario { get; set; }
		public string Clave { get; set; }
		public DateTime FechaRegistro { get; set; }
		public string HoraRegistro { get; set; }
	}
}

