//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Encuesta.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//
using System;

namespace HospiEnCasa.App.Dominio
{
	public class Encuesta 
	{
		public string Sintomas { get; set; }
		public string TipoCita { get; set; }
		public string IdPaciente { get; set; }
		public DateTime Fecha { get; set; }
	}	
}

