//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Medico.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//

namespace HospiEnCasa.App.Dominio
{
	public class Medico : Persona
	{
		//public string Id { get; set; }
		public string IdM { get; set; }
		public string Especialidad { get; set; }
		public string RegistroProfesional { get; set; }
		public string Turno { get; set; }
	}
}

