//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Paciente.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//

namespace HospiEnCasa.App.Dominio
{
	public class Paciente : Persona
	{
		public string Patologia { get; set; }
		public string FamiliarContacto { get; set; }
		public int Edad { get; set; }
		public string DireccionResidencia { get; set; }
		public string IdResponsable { get; set; }
		public string HistoriaClinica { get; set; }
	}
}
