//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : PagadorResponsable.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//

namespace HospiEnCasa.App.Dominio
{
	public class PagadorResponsable 
	{
		//public string Id { get; set; }
		public string IdP { get; set; }
		public string NombreResponsable { get; set; }
		public string Convenio { get; set; }
		public string TipoEmpresa { get; set; }
	}
}

