//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//

namespace HospiEnCasa.App.Dominio
{
	public class Persona 
	{
		public string Id { get; set; }
		public string Nombre1 { get; set; }
		public string Nombre2 { get; set; }
		public string Apellido1 { get; set; }
		public string Apellido2 { get; set; }
		public string EmailPte { get; set; }
		public string TelefonoPte { get; set; }
		public Genero Genero { get; set; }
	}
}

