//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Sede.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//

namespace HospiEnCasa.App.Dominio
{
	public class Sede 
	{
		public string IdSede { get; set; }
		public string DireccionSede { get; set; }
		public string TelefonoSede { get; set; }
		public string CiudadSede { get; set; }
		public string DepartamentoSede { get; set; }
	}
}

