//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Servicio.cs
//  @ Date : 18/09/2021
//  @ Author : 
//
//

namespace HospiEnCasa.App.Dominio
{
	public class Servicio {
		public string MedicinaGeneral { get; set; }
		public string MedicinaHomeopatica { get; set; }
		public string Otro { get; set; }
		public string Laboratorio { get; set; }
}
}

